name: iqnet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.6
  jiffy: ^5.0.0
  get_storage: ^2.0.3
  dotenv: ^4.0.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - .env
    - assets/